### PR TITLE
Feature/logout user ratings

### PR DESCRIPTION
**Pull request by TimNguyen21**
## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Styling- no new features
- [ ] Refactoring- no new features

## Detailed Description
- Reset userRatings to default when user logout

## Why is this change required? What problem does it solve?
- Need state to revert to default when user logout

## Files modified:
- reducers/userRatings.js

### CODE REVIEW

**Comment by megan-venetianer** [comment]
Great job, looks good!

**Comment by hborrelli1** [comment]
Maybe I'm missing it, but what is this PR doing? It looks like there were just a couple props added and then removed?

**Comment by TimNguyen21** [comment]
> Maybe I'm missing it, but what is this PR doing? It looks like there were just a couple props added and then removed?

I just changed the default state from default: state to state = [].  By doing this, when user is logged out, then the state revert to default as an empty array.  If that was not there, the default state would still be the current user ratings in that state.

**Comment by hborrelli1** [comment]
> > Maybe I'm missing it, but what is this PR doing? It looks like there were just a couple props added and then removed?
> 
> I just changed the default state from default: state to state = []. By doing this, when user is logged out, then the state revert to default as an empty array. If that was not there, the default state would still be the current user ratings in that state.

I missed that, my bad! Nice job!

**Pull request merged**
